In [1]:
import pandas as pd
import numpy as np
pd.set_option('max_columns', 120)
pd.set_option('max_colwidth', 5000)


import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rcParams['figure.figsize'] = (12,8)

In [2]:

df = pd.read_csv('prosperLoanData.csv', low_memory=False) 
half_count = len(df) / 2
df = df.dropna(thresh=half_count,axis=1) # Drop any column with more than 50% missing values

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 69 columns):
ListingKey                            113937 non-null object
ListingNumber                         113937 non-null int64
ListingCreationDate                   113937 non-null object
Term                                  113937 non-null int64
LoanStatus                            113937 non-null object
BorrowerAPR                           113912 non-null float64
BorrowerRate                          113937 non-null float64
LenderYield                           113937 non-null float64
EstimatedEffectiveYield               84853 non-null float64
EstimatedLoss                         84853 non-null float64
EstimatedReturn                       84853 non-null float64
ProsperRating (numeric)               84853 non-null float64
ProsperRating (Alpha)                 84853 non-null object
ProsperScore                          84853 non-null float64
ListingCategory (numeric)             113937 non-null int64
BorrowerState                         108422 non-null object
Occupation                            110349 non-null object
EmploymentStatus                      111682 non-null object
EmploymentStatusDuration              106312 non-null float64
IsBorrowerHomeowner                   113937 non-null bool
CurrentlyInGroup                      113937 non-null bool
DateCreditPulled                      113937 non-null object
CreditScoreRangeLower                 113346 non-null float64
CreditScoreRangeUpper                 113346 non-null float64
FirstRecordedCreditLine               113240 non-null object
CurrentCreditLines                    106333 non-null float64
OpenCreditLines                       106333 non-null float64
TotalCreditLinespast7years            113240 non-null float64
OpenRevolvingAccounts                 113937 non-null int64
OpenRevolvingMonthlyPayment           113937 non-null float64
InquiriesLast6Months                  113240 non-null float64
TotalInquiries                        112778 non-null float64
CurrentDelinquencies                  113240 non-null float64
AmountDelinquent                      106315 non-null float64
DelinquenciesLast7Years               112947 non-null float64
PublicRecordsLast10Years              113240 non-null float64
PublicRecordsLast12Months             106333 non-null float64
RevolvingCreditBalance                106333 non-null float64
BankcardUtilization                   106333 non-null float64
AvailableBankcardCredit               106393 non-null float64
TotalTrades                           106393 non-null float64
TradesNeverDelinquent (percentage)    106393 non-null float64
TradesOpenedLast6Months               106393 non-null float64
DebtToIncomeRatio                     105383 non-null float64
IncomeRange                           113937 non-null object
IncomeVerifiable                      113937 non-null bool
StatedMonthlyIncome                   113937 non-null float64
LoanKey                               113937 non-null object
LoanCurrentDaysDelinquent             113937 non-null int64
LoanMonthsSinceOrigination            113937 non-null int64
LoanNumber                            113937 non-null int64
LoanOriginalAmount                    113937 non-null int64
LoanOriginationDate                   113937 non-null object
LoanOriginationQuarter                113937 non-null object
MemberKey                             113937 non-null object
MonthlyLoanPayment                    113937 non-null float64
LP_CustomerPayments                   113937 non-null float64
LP_CustomerPrincipalPayments          113937 non-null float64
LP_InterestandFees                    113937 non-null float64
LP_ServiceFees                        113937 non-null float64
LP_CollectionFees                     113937 non-null float64
LP_GrossPrincipalLoss                 113937 non-null float64
LP_NetPrincipalLoss                   113937 non-null float64
LP_NonPrincipalRecoverypayments       113937 non-null float64
PercentFunded                         113937 non-null float64
Recommendations                       113937 non-null int64
InvestmentFromFriendsCount            113937 non-null int64
InvestmentFromFriendsAmount           113937 non-null float64
Investors                             113937 non-null int64
dtypes: bool(3), float64(41), int64(11), object(14)
memory usage: 57.7+ MB

In [4]:
df.head()

,ListingKey,ListingNumber,ListingCreationDate,Term,LoanStatus,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,LoanCurrentDaysDelinquent,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,36,Completed,0.16516,0.1580,0.1380,NaN,NaN,NaN,NaN,NaN,NaN,0,CO,Other,Self-employed,2.0,True,True,2007-08-26 18:41:46.780000000,640.0,659.0,2001-10-11 00:00:00,5.0,4.0,12.0,1,24.0,3.0,3.0,2.0,472.0,4.0,0.0,0.0,0.0,0.00,1500.0,11.0,0.81,0.0,0.17,"$25,000-49,999",True,3083.333333,E33A3400205839220442E84,0,78,19141,9425,2007-09-12 00:00:00,Q3 2007,1F3E3376408759268057EDA,330.43,11396.14,9425.00,1971.14,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,36,Current,0.12016,0.0920,0.0820,0.07960,0.0249,0.05470,6.0,A,7.0,2,CO,Professional,Employed,44.0,False,False,2014-02-27 08:28:14,680.0,699.0,1996-03-18 00:00:00,14.0,14.0,29.0,13,389.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,3989.0,0.21,10266.0,29.0,1.00,2.0,0.18,"$50,000-74,999",True,6125.000000,9E3B37071505919926B1D82,0,0,134815,10000,2014-03-03 00:00:00,Q1 2014,1D13370546739025387B2F4,318.93,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,81716,2007-01-05 15:00:47.090000000,36,Completed,0.28269,0.2750,0.2400,NaN,NaN,NaN,NaN,NaN,NaN,0,GA,Other,Not available,NaN,False,True,2007-01-02 14:09:10.060000000,480.0,499.0,2002-07-27 00:00:00,NaN,NaN,3.0,0,0.0,0.0,1.0,1.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.06,Not displayed,True,2083.333333,6954337960046817851BCB2,0,86,6466,3001,2007-01-17 00:00:00,Q1 2007,5F7033715035555618FA612,123.32,4186.63,3001.00,1185.63,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,36,Current,0.12528,0.0974,0.0874,0.08490,0.0249,0.06000,6.0,A,9.0,16,GA,Skilled Labor,Employed,113.0,True,False,2012-10-22 11:02:32,800.0,819.0,1983-02-28 00:00:00,5.0,5.0,29.0,7,115.0,0.0,1.0,4.0,10056.0,14.0,0.0,0.0,1444.0,0.04,30754.0,26.0,0.76,0.0,0.15,"$25,000-49,999",True,2875.000000,A0393664465886295619C51,0,16,77296,10000,2012-11-01 00:00:00,Q4 2012,9ADE356069835475068C6D2,321.45,5143.20,4091.09,1052.11,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,36,Current,0.24614,0.2085,0.1985,0.18316,0.0925,0.09066,3.0,D,4.0,2,MN,Executive,Employed,44.0,True,False,2013-09-14 18:38:44,680.0,699.0,2004-02-20 00:00:00,19.0,19.0,49.0,6,220.0,1.0,9.0,0.0,0.0,0.0,0.0,0.0,6193.0,0.81,695.0,39.0,0.95,2.0,0.26,"$100,000+",True,9583.333333,A180369302188889200689E,0,6,102670,15000,2013-09-20 00:00:00,Q3 2013,36CE356043264555721F06C,563.97,2819.85,1563.22,1256.63,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20

In [5]:
df.shape

(113937, 69)

In [6]:
df["ProsperRating (numeric)"].fillna(df["ProsperRating (numeric)"].median(), inplace=True)
df["ProsperScore"].fillna(df["ProsperScore"].median(), inplace=True)


df["ProsperRating (numeric)"].isnull().sum(), df["ProsperScore"].isnull().sum()

(0, 0)

In [7]:
df.dropna(subset=["EmploymentStatusDuration", "CreditScoreRangeLower", "FirstRecordedCreditLine", "CurrentCreditLines",
                  "TotalCreditLinespast7years"], inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 106290 entries, 0 to 113936
Data columns (total 69 columns):
ListingKey                            106290 non-null object
ListingNumber                         106290 non-null int64
ListingCreationDate                   106290 non-null object
Term                                  106290 non-null int64
LoanStatus                            106290 non-null object
BorrowerAPR                           106290 non-null float64
BorrowerRate                          106290 non-null float64
LenderYield                           106290 non-null float64
EstimatedEffectiveYield               84834 non-null float64
EstimatedLoss                         84834 non-null float64
EstimatedReturn                       84834 non-null float64
ProsperRating (numeric)               106290 non-null float64
ProsperRating (Alpha)                 84834 non-null object
ProsperScore                          106290 non-null float64
ListingCategory (numeric)             106290 non-null int64
BorrowerState                         104554 non-null object
Occupation                            104963 non-null object
EmploymentStatus                      106290 non-null object
EmploymentStatusDuration              106290 non-null float64
IsBorrowerHomeowner                   106290 non-null bool
CurrentlyInGroup                      106290 non-null bool
DateCreditPulled                      106290 non-null object
CreditScoreRangeLower                 106290 non-null float64
CreditScoreRangeUpper                 106290 non-null float64
FirstRecordedCreditLine               106290 non-null object
CurrentCreditLines                    106290 non-null float64
OpenCreditLines                       106290 non-null float64
TotalCreditLinespast7years            106290 non-null float64
OpenRevolvingAccounts                 106290 non-null int64
OpenRevolvingMonthlyPayment           106290 non-null float64
InquiriesLast6Months                  106290 non-null float64
TotalInquiries                        106290 non-null float64
CurrentDelinquencies                  106290 non-null float64
AmountDelinquent                      106290 non-null float64
DelinquenciesLast7Years               106290 non-null float64
PublicRecordsLast10Years              106290 non-null float64
PublicRecordsLast12Months             106290 non-null float64
RevolvingCreditBalance                106290 non-null float64
BankcardUtilization                   106290 non-null float64
AvailableBankcardCredit               106290 non-null float64
TotalTrades                           106290 non-null float64
TradesNeverDelinquent (percentage)    106290 non-null float64
TradesOpenedLast6Months               106290 non-null float64
DebtToIncomeRatio                     97886 non-null float64
IncomeRange                           106290 non-null object
IncomeVerifiable                      106290 non-null bool
StatedMonthlyIncome                   106290 non-null float64
LoanKey                               106290 non-null object
LoanCurrentDaysDelinquent             106290 non-null int64
LoanMonthsSinceOrigination            106290 non-null int64
LoanNumber                            106290 non-null int64
LoanOriginalAmount                    106290 non-null int64
LoanOriginationDate                   106290 non-null object
LoanOriginationQuarter                106290 non-null object
MemberKey                             106290 non-null object
MonthlyLoanPayment                    106290 non-null float64
LP_CustomerPayments                   106290 non-null float64
LP_CustomerPrincipalPayments          106290 non-null float64
LP_InterestandFees                    106290 non-null float64
LP_ServiceFees                        106290 non-null float64
LP_CollectionFees                     106290 non-null float64
LP_GrossPrincipalLoss                 106290 non-null float64
LP_NetPrincipalLoss                   106290 non-null float64
LP_NonPrincipalRecoverypayments       106290 non-null float64
PercentFunded                         106290 non-null float64
Recommendations                       106290 non-null int64
InvestmentFromFriendsCount            106290 non-null int64
InvestmentFromFriendsAmount           106290 non-null float64
Investors                             106290 non-null int64
dtypes: bool(3), float64(41), int64(11), object(14)
memory usage: 54.6+ MB

In [9]:
df_debt_income_null = df[df["DebtToIncomeRatio"].isnull()]

df_debt_income_null[:5]

,ListingKey,ListingNumber,ListingCreationDate,Term,LoanStatus,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,LoanCurrentDaysDelinquent,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
40,10A43601079743929992413,1167746,2014-01-27 12:02:57.523000000,60,Current,0.19630,0.1725,0.1625,0.15163,0.0724,0.07923,4.0,C,4.0,1,WA,Other,Self-employed,276.0,False,False,2014-01-25 10:47:25,680.0,699.0,1985-12-20 00:00:00,10.0,9.0,28.0,10,1233.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,61284.0,0.46,69166.0,28.0,1.00,2.0,NaN,"$100,000+",False,12750.0,91A33705770133108E299C1,0,2,129161,15000,2014-01-29 00:00:00,Q1 2014,ACFF370458072043753CE79,374.81,374.8100,162.14,212.6700,-12.33,0.00,0.00,0.00,0.0,1.0,0,0,0.0,3
69,0F37360159310530849DA23,1162592,2014-01-25 12:07:54.537000000,60,Current,0.13636,0.1139,0.1039,0.09989,0.0349,0.06499,6.0,A,11.0,1,IL,Investor,Self-employed,12.0,True,True,2014-01-25 11:51:41,700.0,719.0,1995-08-01 00:00:00,5.0,5.0,21.0,3,373.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,19961.0,0.79,5039.0,21.0,1.00,0.0,NaN,"$25,000-49,999",False,2700.0,B08137048491184083D747A,0,2,128889,9000,2014-01-29 00:00:00,Q1 2014,87D0340317005703964722E,197.44,194.6315,115.99,78.6415,-7.15,0.00,0.00,0.00,0.0,1.0,0,0,0.0,1
78,0DFE3425061927556BB8A75,359657,2008-06-29 23:23:40.157000000,36,Chargedoff,0.18454,0.1700,0.1600,NaN,NaN,NaN,4.0,NaN,6.0,3,CA,Realtor,Full-time,68.0,True,False,2008-06-29 23:13:04.860000000,720.0,739.0,1995-11-29 00:00:00,14.0,14.0,26.0,9,962.0,4.0,11.0,0.0,0.0,0.0,0.0,0.0,33572.0,0.73,9355.0,24.0,1.00,1.0,NaN,$0,False,0.0,B8483424568930207C77772,1918,68,33852,4800,2008-07-08 00:00:00,Q3 2008,D77734052911579724BCDD5,171.13,684.5200,418.38,266.1400,-15.66,0.00,4381.62,4381.62,0.0,1.0,0,0,0.0,115
100,0F67356860455769574096F,704916,2013-01-25 11:48:26.040000000,36,Chargedoff,0.35356,0.3134,0.3034,0.27600,0.1575,0.11850,1.0,HR,3.0,13,CA,Other,Not employed,12.0,False,False,2013-01-11 12:10:13,720.0,739.0,2000-09-10 00:00:00,3.0,3.0,10.0,3,56.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,5641.0,0.22,19359.0,4.0,1.00,1.0,NaN,Not employed,False,0.0,9D203674230576864DAB261,314,14,82947,4000,2013-01-30 00:00:00,Q1 2013,CEE83539008163122ED9B62,172.76,345.5200,144.77,200.7500,-6.41,0.00,3855.23,3855.23,0.0,1.0,0,0,0.0,73
103,0F843543787869030F017F8,579737,2012-04-17 11:58:52.270000000,36,Chargedoff,0.26681,0.2287,0.2187,0.21340,0.0990,0.11440,3.0,D,2.0,3,CO,Truck Driver,Self-employed,29.0,True,False,2012-04-17 11:58:46,680.0,699.0,1993-10-26 00:00:00,9.0,7.0,21.0,1,699.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28228.0,0.98,502.0,18.0,0.77,0.0,NaN,"$50,000-74,999",False,5000.0,3AB03648859759387133670,384,23,63925,15000,2012-04-19 00:00:00,Q2 2012,F11E34621201188152DD3DA,579.63,3968.8900,1119.05,2849.8400,-49.41,-813.65,13880.95,13880.95,1600.0,1.0,0,0,0.0,21

In [10]:
df.drop(["ListingKey", "ListingNumber", "LoanKey", "LoanNumber"], axis=1, inplace=True)

In [11]:
df.drop(["ListingCreationDate",  "DateCreditPulled", "LoanOriginationDate", "LoanOriginationQuarter", "MemberKey"],
        axis=1, inplace=True)

In [12]:
df.drop(["LoanCurrentDaysDelinquent",  "LoanMonthsSinceOrigination", "LP_CustomerPayments",
         "LP_CustomerPrincipalPayments", "LP_InterestandFees", "LP_ServiceFees", "LP_CollectionFees", "LP_GrossPrincipalLoss",
         "LP_NetPrincipalLoss", "LP_NonPrincipalRecoverypayments"], axis=1, inplace=True)

In [13]:
df.drop(['LenderYield', 'EstimatedEffectiveYield','EstimatedLoss', 'EstimatedReturn','ProsperRating (numeric)',
         'ProsperRating (Alpha)','ProsperScore','Occupation','EmploymentStatus'],axis=1, inplace=True)

In [14]:
df.drop(['CurrentlyInGroup','FirstRecordedCreditLine','TotalCreditLinespast7years','OpenRevolvingAccounts',
         'OpenRevolvingMonthlyPayment','InquiriesLast6Months','TotalInquiries'],axis=1, inplace=True)

In [15]:
df.drop(['DelinquenciesLast7Years','PublicRecordsLast10Years','PublicRecordsLast12Months',
        'RevolvingCreditBalance','BankcardUtilization','TotalTrades','TradesNeverDelinquent (percentage)'],axis=1, inplace=True)

In [16]:
df.drop(['TradesOpenedLast6Months','IncomeVerifiable','StatedMonthlyIncome','PercentFunded',
        'Recommendations','InvestmentFromFriendsCount','InvestmentFromFriendsAmount','Investors'],axis=1, inplace=True)

In [17]:
print(df['CreditScoreRangeLower'].unique())
print(df['CreditScoreRangeUpper'].unique())

[ 640.  680.  800.  740.  700.  820.  660.  620.  720.  760.  780.  600.
  580.  560.  520.  840.  860.  540.  880.]
[ 659.  699.  819.  759.  719.  839.  679.  639.  739.  779.  799.  619.
  599.  579.  539.  859.  879.  559.  899.]

In [18]:
#creditRange_columns = ['CreditScoreRangeLower','CreditScoreRangeUpper']

df['crRange_average'] = (df['CreditScoreRangeLower'] + df['CreditScoreRangeUpper']) / 2

In [19]:
cols = ['CreditScoreRangeLower','CreditScoreRangeUpper','crRange_average']
df[cols].head()

   CreditScoreRangeLower  CreditScoreRangeUpper  crRange_average
0                  640.0                  659.0            649.5
1                  680.0                  699.0            689.5
3                  800.0                  819.0            809.5
4                  680.0                  699.0            689.5
5                  740.0                  759.0            749.5

In [20]:
drop_cols = ['CreditScoreRangeLower','CreditScoreRangeUpper']
df= df.drop(drop_cols, axis=1)
df.shape

(106290, 18)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 106290 entries, 0 to 113936
Data columns (total 18 columns):
Term                         106290 non-null int64
LoanStatus                   106290 non-null object
BorrowerAPR                  106290 non-null float64
BorrowerRate                 106290 non-null float64
ListingCategory (numeric)    106290 non-null int64
BorrowerState                104554 non-null object
EmploymentStatusDuration     106290 non-null float64
IsBorrowerHomeowner          106290 non-null bool
CurrentCreditLines           106290 non-null float64
OpenCreditLines              106290 non-null float64
CurrentDelinquencies         106290 non-null float64
AmountDelinquent             106290 non-null float64
AvailableBankcardCredit      106290 non-null float64
DebtToIncomeRatio            97886 non-null float64
IncomeRange                  106290 non-null object
LoanOriginalAmount           106290 non-null int64
MonthlyLoanPayment           106290 non-null float64
crRange_average              106290 non-null float64
dtypes: bool(1), float64(11), int64(3), object(3)
memory usage: 14.7+ MB

In [22]:
df["LoanStatus"].value_counts()

Current                   56566
Completed                 33530
Chargedoff                10632
Defaulted                  3289
Past Due (1-15 days)        806
Past Due (31-60 days)       363
Past Due (61-90 days)       313
Past Due (91-120 days)      304
Past Due (16-30 days)       265
FinalPaymentInProgress      205
Past Due (>120 days)         16
Cancelled                     1
Name: LoanStatus, dtype: int64

In [23]:
meaning = [
    "Loan is up to date on current payments.",
    "Loan has been fully paid off.",
    "Loan for which there is no longer a reasonable expectation of further payments.",
    "Loan is defaulted on and no payment has been made.",
    "The loan is past due 15 days.",
    "The loan is past due 60 days.",
    "The loan is past due 90 days.",
    "The loan is past due 120 days.",
    "The loan is past due 16-30 days.",
    "Final Payment in progress",
    "The loan is past due >120 days.",
    "Cancelled."]
status, count = df["LoanStatus"].value_counts().index, df["LoanStatus"].value_counts().values

status_explanation = pd.DataFrame({'Loan Status': status,'Count': count,'Meaning': meaning})[['Loan Status','Count','Meaning']]
status_explanation

,Loan Status,Count,Meaning
0,Current,56566,Loan is up to date on current payments.
1,Completed,33530,Loan has been fully paid off.
2,Chargedoff,10632,Loan for which there is no longer a reasonable expectation of further payments.
3,Defaulted,3289,Loan is defaulted on and no payment has been made.
4,Past Due (1-15 days),806,The loan is past due 15 days.
5,Past Due (31-60 days),363,The loan is past due 60 days.
6,Past Due (61-90 days),313,The loan is past due 90 days.
7,Past Due (91-120 days),304,The loan is past due 120 days.
8,Past Due (16-30 days),265,The loan is past due 16-30 days.
9,FinalPaymentInProgress,205,Final Payment in progress
10,Past Due (>120 days),16,The loan is past due >120 days.
11,Cancelled,1,Cancelled.

In [24]:
df = df[(df["LoanStatus"] == "Completed") |
                            (df["LoanStatus"] == "Chargedoff")]

mapping_dictionary = {"LoanStatus":{ "Completed": 1, "Chargedoff": 0}}
df = df.replace(mapping_dictionary)

In [25]:
df = df.loc[:,df.apply(pd.Series.nunique) != 1]

In [26]:
for col in df.columns:
    if (len(df[col].unique()) < 4):
        print(df[col].value_counts())
        print()

36    39130
60     3510
12     1522
Name: Term, dtype: int64
()
1    33530
0    10632
Name: LoanStatus, dtype: int64
()
False    22626
True     21536
Name: IsBorrowerHomeowner, dtype: int64
()

In [27]:
print(df.shape[1])

print("We've been able to reduced the features to => {}".format(df.shape[1]))

18
We've been able to reduced the features to => 18

In [28]:
df.to_csv("filtered_df.csv",index=False)

In [29]:
filtered_df = pd.read_csv('filtered_df.csv')
print(filtered_df.shape)
filtered_df.head()

(44162, 18)

,Term,LoanStatus,BorrowerAPR,BorrowerRate,ListingCategory (numeric),BorrowerState,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentCreditLines,OpenCreditLines,CurrentDelinquencies,AmountDelinquent,AvailableBankcardCredit,DebtToIncomeRatio,IncomeRange,LoanOriginalAmount,MonthlyLoanPayment,crRange_average
0,36,1,0.16516,0.1580,0,CO,2.0,True,5.0,4.0,2.0,472.0,1500.0,0.17,"$25,000-49,999",9425,330.43,649.5
1,36,1,0.15033,0.1325,0,NaN,19.0,False,2.0,2.0,3.0,2224.0,2580.0,0.27,"$1-24,999",1000,33.81,649.5
2,36,1,0.21488,0.2075,0,MI,36.0,False,4.0,4.0,1.0,5200.0,1366.0,0.09,"$25,000-49,999",3000,112.64,629.5
3,60,1,0.30748,0.2809,1,NY,25.0,False,7.0,6.0,0.0,0.0,3619.0,0.11,"$25,000-49,999",4000,124.76,669.5
4,36,1,0.11296,0.0920,1,CO,10.0,True,16.0,16.0,0.0,0.0,30794.0,0.26,"$75,000-99,999",4000,0.00,709.5

In [30]:
null_counts = filtered_df.isnull().sum()
print("Number of null values in each column:\n{}".format(null_counts))

Number of null values in each column:
Term                            0
LoanStatus                      0
BorrowerAPR                     0
BorrowerRate                    0
ListingCategory (numeric)       0
BorrowerState                1550
EmploymentStatusDuration        0
IsBorrowerHomeowner             0
CurrentCreditLines              0
OpenCreditLines                 0
CurrentDelinquencies            0
AmountDelinquent                0
AvailableBankcardCredit         0
DebtToIncomeRatio            3865
IncomeRange                     0
LoanOriginalAmount              0
MonthlyLoanPayment              0
crRange_average                 0
dtype: int64

In [31]:
filtered_df = filtered_df.drop("DebtToIncomeRatio",axis=1)
filtered_df = filtered_df.drop("BorrowerState",axis=1)
filtered_df = filtered_df.drop("IncomeRange",axis=1)
filtered_df = filtered_df.dropna()

In [32]:
filtered_df.columns.tolist()

['Term',
 'LoanStatus',
 'BorrowerAPR',
 'BorrowerRate',
 'ListingCategory (numeric)',
 'EmploymentStatusDuration',
 'IsBorrowerHomeowner',
 'CurrentCreditLines',
 'OpenCreditLines',
 'CurrentDelinquencies',
 'AmountDelinquent',
 'AvailableBankcardCredit',
 'LoanOriginalAmount',
 'MonthlyLoanPayment',
 'crRange_average']

In [33]:

print("Data types and their frequency\n{}".format(filtered_df.dtypes.value_counts()))

Data types and their frequency
float64    10
int64       4
bool        1
dtype: int64

In [34]:
object_columns_df = filtered_df.select_dtypes(include=['object'])
print(object_columns_df.iloc[0])

Series([], Name: 0, dtype: float64)

In [35]:
for name in ['ListingCategory (numeric)']:
    print("Unique Values in column: {}\n".format(name))
    print(filtered_df[name].value_counts(),'\n')

Unique Values in column: ListingCategory (numeric)

(1     16815
0      8159
7      5772
3      3954
2      3102
4      2194
6      1479
5       715
13      574
15      357
18      208
19      192
14      176
20      165
16       92
11       63
10       43
8        40
9        28
12       18
17       16
Name: ListingCategory (numeric), dtype: int64, '\n')

In [36]:
cat_columns = ["IsBorrowerHomeowner", "EmploymentStatusDuration", "Term"]
dummy_df = pd.get_dummies(filtered_df[cat_columns])
filtered_df = pd.concat([filtered_df, dummy_df], axis=1)
filtered_df = filtered_df.drop(cat_columns, axis=1)

In [37]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44162 entries, 0 to 44161
Data columns (total 12 columns):
LoanStatus                   44162 non-null int64
BorrowerAPR                  44162 non-null float64
BorrowerRate                 44162 non-null float64
ListingCategory (numeric)    44162 non-null int64
CurrentCreditLines           44162 non-null float64
OpenCreditLines              44162 non-null float64
CurrentDelinquencies         44162 non-null float64
AmountDelinquent             44162 non-null float64
AvailableBankcardCredit      44162 non-null float64
LoanOriginalAmount           44162 non-null int64
MonthlyLoanPayment           44162 non-null float64
crRange_average              44162 non-null float64
dtypes: float64(9), int64(3)
memory usage: 4.4 MB

In [38]:
filtered_df.to_csv("cleaned_loans.csv",index=False)

In [39]:

loans = pd.read_csv("cleaned_loans.csv")
print(loans.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44162 entries, 0 to 44161
Data columns (total 12 columns):
LoanStatus                   44162 non-null int64
BorrowerAPR                  44162 non-null float64
BorrowerRate                 44162 non-null float64
ListingCategory (numeric)    44162 non-null int64
CurrentCreditLines           44162 non-null float64
OpenCreditLines              44162 non-null float64
CurrentDelinquencies         44162 non-null float64
AmountDelinquent             44162 non-null float64
AvailableBankcardCredit      44162 non-null float64
LoanOriginalAmount           44162 non-null int64
MonthlyLoanPayment           44162 non-null float64
crRange_average              44162 non-null float64
dtypes: float64(9), int64(3)
memory usage: 4.0 MB
None

In [40]:
import pandas as pd
import numpy

# Predict that all loans will be paid off on time.
predictions = pd.Series(numpy.ones(loans.shape[0]))
# False positives.
fp_filter = (predictions == 1) & (loans["LoanStatus"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["LoanStatus"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["LoanStatus"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["LoanStatus"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

1
1

In [41]:
## 4. Logistic Regression ##

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
cols = loans.columns
train_cols = cols.drop("LoanStatus")
features = loans[train_cols]
target = loans["LoanStatus"]
lr.fit(features, target)
predictions = lr.predict(features)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_predict, KFold
lr = LogisticRegression()
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(lr, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["LoanStatus"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["LoanStatus"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["LoanStatus"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["LoanStatus"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0
0

In [45]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import cross_val_predict
penalty = {
    0: 10,
    1: 1
}

lr = LogisticRegression(class_weight=penalty)
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(lr, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["LoanStatus"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["LoanStatus"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["LoanStatus"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["LoanStatus"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0
0

In [46]:
## 8. Random forests ##

from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_predict
rf = RandomForestClassifier(class_weight="balanced", random_state=1)
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(rf, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["LoanStatus"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["LoanStatus"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["LoanStatus"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["LoanStatus"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0
0